{% set name = "gridmarthe" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/brgm/hydrogeological-modelling/marthe-tools/gridmarthe/-/archive/v{{ version }}/gridmarthe-v{{ version }}.tar.gz
  sha256: 1b87e8125bf4c7b21d484f6d2b757c9c8489b09ae4ebb321f61d92b9dc047a11

build:
  number: 1
  skip: True  # [py<310]
  # entry_points:
  #     - ncmart = gridmarthe:scripts.ncmart
  #     - cleanmgrid =gridmarthe:scripts.cleanmgrid

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - ninja
    - meson
  host:
    - python
    - pip
    - charset-normalizer
    - meson
    - meson-python
    - numpy
  run:
    - python
    - pandas
    - h5netcdf
    - xarray
    - geopandas
    - shapely
    - matplotlib-base

test:
  imports:
    - {{ name }}
  requires:
    - pip
#    - pytest
#  source_files:
#    - tests
  commands:
    - pip check
    - python -c "import gridmarthe"
#    - pytest tests/test_gridmarthe.py

about:
  home: https://gitlab.com/brgm/hydrogeological-modelling/marthe-tools/gridmarthe.git
  summary: 'Simple, fast read/write Python package for MartheGrids'
  description: |
    Full support of gridmarthe read operations by wrapping MARTHE fortran read/write module,
    allowing fast reading of marthe grid file (v9, v8, constant_data, etc.), for any variable.
    Release under GNU General Public License version 3.0
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  doc_url: 'https://gridmarthe.readthedocs.io/en/latest/'

extra:
  recipe-maintainers:
    - manlaya
